#!/usr/bin/env bash
# scripts/sync-supabase-env.sh (D-18, R-3)
# Parses `supabase status -o env` output -> writes .env.local. NEVER modifies .env.
# Derives DATABASE_POOL_URL from DATABASE_URL (locally identical; prepare=false posture).
set -euo pipefail

if ! docker info >/dev/null 2>&1; then
  echo "ERROR: Docker daemon unreachable. Start Docker Desktop then retry." >&2
  exit 1
fi

OUT=.env.local
TMP="$OUT.tmp"

pnpm supabase status -o env \
  --override-name api.url=NEXT_PUBLIC_SUPABASE_URL \
  --override-name anon_key=NEXT_PUBLIC_SUPABASE_ANON_KEY \
  --override-name service_role_key=SUPABASE_SERVICE_ROLE_KEY \
  --override-name db.url=DATABASE_URL \
  > "$TMP"

DB_URL=$(grep '^DATABASE_URL=' "$TMP" | head -n1 | cut -d= -f2-)
if [ -z "$DB_URL" ]; then
  echo "ERROR: supabase status did not emit DATABASE_URL. Is 'pnpm db:start' running?" >&2
  trash "$TMP" 2>/dev/null || rm -f "$TMP"
  exit 2
fi
echo "DATABASE_POOL_URL=$DB_URL" >> "$TMP"

{
  echo "# Auto-generated by scripts/sync-supabase-env.sh — do not edit by hand."
  echo "# Re-run 'pnpm db:sync-env' after 'pnpm db:start' or 'pnpm db:reset'."
  cat "$TMP"
} > "$OUT"
trash "$TMP" 2>/dev/null || rm -f "$TMP"

echo "Wrote $OUT"
